--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ImmoDevs/Trampoline
build-by-default: true
branches:
- main
projects:
  Trampoline:
    path: ""
    icon: "icon.png"
    lint:
      phpstan: false
...
